Add host Global
opawg/podcast-hosts pull request #32
Opened 2022-06-17 22:55 UTC by jenmcquade

Hi there 👋. I ran into an issue where I was checking for Global.com podcasts, but since they piggyback off of Spreaker for enclosures, I was getting a false positive. Here's an example feed:
https://podcast.global.com/show/4467866/episodes/feed

This additional pattern will match Spreaker API enclosure files and Global RSS feeds.

Let me know if you have any questions. Thanks!

2022-06-18 16:22 UTC, johnspurlock commented
Thanks for pointing out how to id Global feeds! (podcast.global.com)

This one is tricky though, your proposed addition...

```json
    {
      "pattern": "api.spreaker.com",
      "rss-pattern": "podcast.global.com",
      "hostname": "Global",
      "retailer": "0",
      "iab": "0",
      "abilities_stats": "1",
      "abilities_tracking": "1",
      "abilities_dynamicaudio": "1",
      "hosturl": "https://global.com/",
      "hostprivacyurl": "https://global.com/legal/privacy-policy",
      "notes": "",
      "pi-slug": ""
    }
```

... conflicts with the existing entry for Spreaker in the media file pattern:

```json
    {
        "pattern": "spreaker.com",
        "rss-pattern": "spreaker.com",
        "hostname": "Spreaker",
        "retailer": "1",
        "iab": "1",
        "abilities_stats": "1",
        "abilities_tracking": "0",
        "abilities_dynamicaudio": "1",
        "hosturl": "https:\/\/www.spreaker.com\/",
        "hostprivacyurl": "https:\/\/www.spreaker.com\/privacy",
        "notes": "DAI: https:\/\/internetfolks.com\/best-podcast-hosting-for-monetization\/",
        "pi-slug": "Spreaker"
    },
```

Given just a media file url, one would not be able to tell if it was Spreaker or Global.

Looking closer at the example feed: https://podcast.global.com/show/4467866/episodes/feed

This is looks like a standard Spreaker show feed, it even has a spreaker show url! https://www.spreaker.com/show/rob-beckett-and-josh-widdicombes-lockdow

Would be interested to know what the [Global Audio Hosting](https://podcast.global.com/login) interface looks like, beyond the login.

If Global is just a white-labeled Spreaker, without even changing the media file urls, I'm not sure how/if this should be represented in the hosts file. 🤔

@jamescridland, what do you think?

2022-06-19 23:35 UTC, bslinger commented
Isn't this the situation that rss-pattern was intended to be used for? Given just a media file url you would not be able to tell if it was Libsyn or LibsynPro either. The only difference in this case is that the Spreaker entry doesn't specify an rss-pattern, but I would suggest the best practise would be to use the entry with best fit, ie. if you can't match on rss-pattern (either because you only have a media URL, or the relevant RSS feed URL does not match) then you would fall back to any matching entry with no specified rss-pattern.

2022-06-19 23:45 UTC, johnspurlock commented
> Isn't this the situation that rss-pattern was intended to be used for? Given just a media file url you would not be able to tell if it was Libsyn or LibsynPro either.

That's a good point, it's similar to the Libsyn setup

> The only difference in this case is that the Spreaker entry doesn't specify an rss-pattern

The existing hosts entry specifies `"spreaker.com"` for an rss-pattern which seems accurate

(example feed: https://www.spreaker.com/show/1433865/episodes/feed)

2022-06-20 00:24 UTC, bslinger commented
> The existing hosts entry specifies "spreaker.com" for an rss-pattern, which seems accurate

Oh, you're right, I was looking at an older version of the file locally where most of the rss-pattern fields are empty. In that case there's no real way to resolve multiple entries matching the media file URL if you don't have the RSS feed URL as well, so I guess it would just be up to the developer to determine which one they want to use.

2022-06-20 01:17 UTC, jamescridland commented
(The LibsynPro setup is now, as far as I know, no longer used.)

The files are hosted by Spreaker; but published by Global. What happens here if we remove the clashing `pattern`? That way, the RSS pattern can be used for more granular checks? Should we ensure that `pattern` is always unique?

For one use-case, @johnspurlock 's Big List of Podcast Hosts, I can see these podcasts being classified as Spreaker. Does this help, or does this make life more complicated?

```
    {
      "pattern": "",
      "rss-pattern": "podcast.global.com",
      "hostname": "Global",
      "retailer": "0",
      "iab": "0",
      "abilities_stats": "1",
      "abilities_tracking": "1",
      "abilities_dynamicaudio": "1",
      "hosturl": "https://global.com/",
      "hostprivacyurl": "https://global.com/legal/privacy-policy",
      "notes": "",
      "pi-slug": ""
    }
```

2022-06-20 02:35 UTC, bslinger commented
Even with a unique `pattern` you could end up with multiple matching hosts for a particular enclosure URL, ie. `spreaker.com` vs `api.spreaker.com`, though that of course could be avoided if desired.

Given that in this situation there is no way to unambigiously determine the hosting provider from just the enclosure URL, my preference would be to keep the `pattern` as `spreaker.com` so that filtering by just `pattern` would return all potential hosts, as that result seems like it reflects reality more accurately. Then `rss-pattern` can be used as a more granular check to narrow it down to the actual host.

Allowing for an empty `pattern` could certainly work, but from my end that would mean the cleanest logic when we have both the enclosure URL and the RSS URL would be to always check for a matching `rss-pattern` first, and only use the `pattern` if there was no match, so `pattern` would not get used very much at all.

2022-06-20 21:38 UTC, bslinger commented
I guess it comes down to what problem this file is intending so solve - if it's just to determine who is hosting the actual media files on their infrastructure then you can probably get away with a unique `pattern`. If you want to determine who the actual hosting provider is, ie. whose website did the user actually go to and sign up with, then you would need to account for these more nuanced situations. (For example, if you wanted to track how many podcasts moved from Spreaker to Global or vice versa)

To clarify my stance, Spreaker reached out to us at Podchaser asking if we could correctly reflect podcasts that are hosted by Global vs those hosted by Spreaker, so for our use case it is necessary. If it's decided that these sorts of situations aren't to be reflected in the file then we'll have to create our own fork to allow us to deal with them ourselves.

2022-06-20 22:23 UTC, johnspurlock commented
> I guess it comes down to what problem this file is intending so solve 

Yea exactly - I feel like there needs to be some sort of common understanding of what a retail host is.  For example, where is the Global product page for the hosting product behind podcast.global.com -  here? https://global.com/dax/audio/podcast-publishers/ or here? https://podcast.global.com/login

Perhaps that url should be in the `hosturl` for the new Global entry.

That's why I'm curious to see if anyone has actually seen the product beyond the login page.  Would love to see some screenshots

One of the things I end up doing every month is sorting uncategorized episodes found by domain and looking for as of yet unknown podcast hosts.  And spend a not insignificant time trying to determine whether or not they are a proper retail host (vs a private publishing house or national broadcaster etc)

 > asking if we could correctly reflect podcasts that are hosted by Global vs those hosted by Spreaker

I do think the podcast feed filter is useful info to capture in this hosts file, but my suggestion is that we put some sort of additional clarity around how to use the file, for the benefit of current and future downstream users.

ie change some of the language in https://github.com/opawg/podcast-hosts, remove the "unique" aspect of the media pattern, and clarify/warn that pattern can be used as a first pass (could return more than one candidate), then rss-pattern as a tie-breaker.

So then a new entry for Global would be something like:

```jsonc
    {
      "pattern": "spreaker.com", // to match existing spreaker record, otherwise implies api. is somehow Global-specific
      "rss-pattern": "podcast.global.com",
      "hostname": "Global",
      "retailer": "0", // or "1" pending research
      "iab": "0",
      "abilities_stats": "1",
      "abilities_tracking": "1",
      "abilities_dynamicaudio": "1",
      "hosturl": "https:\/\/global.com\/dax\/audio\/podcast-publishers\/", // or is it somewhere or something else?
      "hostprivacyurl": "https://global.com/legal/privacy-policy",
      "notes": "Uses Spreaker as the underlying platform with basic feed url customization", // after we nail this down
      "pi-slug": ""
    }
```

2022-06-20 23:55 UTC, bslinger commented
That all makes sense to me - I'll see if I can get some additional information about what Global is offering so we can nail down the entry.

2022-06-21 23:20 UTC, bslinger commented
Spreaker has confirmed that Global is not a retailer, they use the whitelabelled CMS provided by Spreaker for their own network of shows. They otherwise have all the same functionality as the Spreaker retail service. They also confirmed that the `hosturl` is appropriate, so with a few changes I think @johnspurlock 's entry above makes sense.

2022-06-21 23:28 UTC, jenmcquade commented
Hi @johnspurlock! I've updated the rule based on a discussion I had with @bslinger and feedback from Spreaker.

2022-06-21 23:32 UTC, johnspurlock commented on src/hosts.json
>        "hostprivacyurl": "https://global.com/legal/privacy-policy",
```suggestion
      "hostprivacyurl": "https:\/\/global.com\/legal\/privacy-policy",
```

2022-06-21 23:33 UTC, johnspurlock requested changes
Url value escaping should match the rest of the file

2022-06-21 23:46 UTC, jenmcquade commented on src/hosts.json
>        "hostprivacyurl": "https://global.com/legal/privacy-policy",
Ah, sorry about that. Updated.

2022-06-21 23:47 UTC, merged

2022-06-21 23:49 UTC, johnspurlock commented
Thanks again!